### ISSUE TITLE
upload not possible

### ISSUE THREAD

**Issue by wawefr** [strahli30/HowTo-use-Docker-Seafile-Plex-NGINX#1]
Hello
Thanks for your job.
I have juste one issue, when I'm connected to Seafile via borwser, I can't upload à file. (Network mistake)
The synchro via windows client is OK
Thanks for your help
Fred

**Comment by homehoster** [comment]
Hello!
I've the same isue. I'm not really sure about the solution, but I'm believe, the reason is in the file [seahub_settings.py]. You have to change at 1fst line from http to https and add the line _SERVICE_URL = 'https://<Domain bspw. seafile.dyn.de>/seafhttp'_

If it not work, there is no mor idea - sorry.

#NUR URL von http auf https ändern
FILE_SERVER_ROOT = "https://<Domain bspw. seafile.dyn.de>/seafhttp"

#diese Zeile noch einfügen
SERVICE_URL = 'https://<Domain bspw. seafile.dyn.de>/seafhttp'

I'm really happy about your ussing my  manual! :-)

Have fun and enjoy
David

**Comment by wawefr** [comment]
Hi David

Lot's of thanks for your help, but I have always the problem.

My config below

I have one other question, if I want to had other "site" via the reverse 
proxy jwilder that you use, what is the procedure?

Many thanks and thank you for your good job

Fred

Le 24/09/2022 18:32, strahli30 a écrit :

> Hello!
> I've the same isue. I'm not really sure about the solution, but I'm 
> believe, the reason is in the file [seahub_settings.py]. You have to 
> change at 1fst line from http to https and add the line _SERVICE_URL = 
> 'https:///seafhttp'_
> 
> If it not work, there is no mor idea - sorry.
> 
> #NUR URL von http auf https ändern
> FILE_SERVER_ROOT = "https:///seafhttp"
> 
> #diese Zeile noch einfügen
> SERVICE_URL = 'https:///seafhttp'
> 
> I'm really happy about your ussing my manual! :-)
> 
> Have fun and enjoy
> David
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/strahli30/HowTo-use-Docker-Seafile-Plex-NGINX/issues/1#issuecomment-1257008241
[2]

**Comment by wawefr** [comment]
![4c3cd8a0](https://user-images.githubusercontent.com/62282235/192135476-acc7c6f0-d7ee-4625-9b86-7a1cda2dd957.png)
My config 
thanks

**Comment by homehoster** [comment]
Hello!

Is then ccnet.conf also changend from http https, e.g.:

_# NUR Service_URL auf https und ohne PortNummer ändern
[General]
SERVICE_URL = https://<Domain bspw. seafile.dyn.de>_

If it not work, there is no mr idea

In order for another container to run with nginx, the following lines must be added to the container's docker-compose.yml in the environment:

      - VIRTUAL_HOST=domain.de # Domain e.g. seafile.dyndns.de
       - VIRTUAL_NETWORK=external # the same network as the NGINX container
       - VIRTUAL_PORT=XX # Port through which the app can be reached
       - LETSENCRYPT_HOST=domain.de # Domain e.g. seafile.dyndns.de
       - LETSENCRYPT_EMAIL=mail@mail.com # an email address, e.g. meinewegwerfadresse@ich.de


Pleas read the manual of your app - I'm not a proffesional :-)

**Comment by wawefr** [comment]
Hi
Thank you very much for your help, but it's still KO with the ccnet.conf modification.
I will stop my research
Thank you again and have a nice day

**Comment by homehoster** [comment]
closed
